### ISSUE TITLE
Crash with Create: The Factory Must Grow

### ISSUE THREAD

**Issue by RyukoM4701** [Amronos/create-addon-compatibility#2] opened 2024-04-21 11:22 UTC
it crashes with the factory must grow 0.8.0b enabled
tried with almost unified versions 0.9.2 and 0.9.3
it doesn't crash when factory must grow is not present, but it's meant to work with it, why does it crash?

**Comment by Amronos** [comment] 2024-04-21 14:03
What other mods do you have installed?
Can you try with the latest version of the mod published a bit ago.

**Comment by RyukoM4701** [comment] 2024-04-21 14:26
- **Past issues, before making a bug report here:**

Originally, I had the mod on my modpack not knowing what it does (I just read it's name and was like how cool, clicked install, lol)
TFMG and Diesel Generators didn't exist on my modpack

Then upon a friends request, I add them and game starts to crash when I click singleplayer button, probably wouldn't work on multiplayer either

Then I tried with only Almost Unified, Create, your mod and TFMB, didn't work either

- **Last test with v0.1.2 after bug report:**

Added it straight up to my modpack, same crash as before

Tried with only these mods: 
forge 47.2.30
almost unified 0.9.3
create 0.5.1f
create addon compat 0.1.2
create steam n rails 1.6.3
create the factory must grow 0.8.0b

didn't work, adding diesel generators didn't change anything either



I sadly can't use Neoforge because literally one singular mod asks for 47.2.xx
and neoforge continues from 47.1.xxx versions so I wonder maybe your mod works fine just on neoforge? idk, honestly I have no idea how java works 

nevermind, it crashes with neoforged too with 6~ mods listed above

**Comment by Amronos** [comment] 2024-04-21 15:23
Can you send the crash report and the logs. As I can't reproduce this issue on my end.

**Comment by RyukoM4701** [comment] 2024-04-21 16:34
https://mclo.gs/Zfc4vNP this one's with neoforge
https://mclo.gs/2wGvqn0 this one's with forge (also tried different java)

**Comment by Amronos** [comment] 2024-04-27 08:40
The probable reason for the crash is that recipes in Create: Addon Compatibility are loaded which need fluids from other mods and give the product as a fluid from Create: The Factory Must Grow. Those mods not being there causes a crash.

As a temporary fix, the following mods can be installed alongside Create: Addon Compatibility, Create, Almost Unified, and Create: The Factory Must Grow:
[Ad Astra](https://modrinth.com/mod/ad-astra)
[Botarium](https://modrinth.com/mod/botarium)
[Create: Diesel Generators](https://modrinth.com/mod/create-diesel-generators)
[Destroy (Create add-on)](https://modrinth.com/mod/destroy)
[Patchouli](https://modrinth.com/mod/patchouli)
[PneumaticCraft: Repressurized](https://modrinth.com/mod/pneumaticcraft-repressurized)
[Resourceful Config](https://modrinth.com/mod/resourceful-config)
[Resourceful Lib](https://modrinth.com/mod/resourceful-lib)

**Comment by Amronos** [comment] 2024-04-30 15:17
fixed in https://github.com/Amronos/createaddoncompatibility/commit/a2a092c50d8c223ae3852d385ac93aab91e2a756

**Closed as completed by Amronos** 2024-04-30 15:17 UTC
Labels: bug, forge, 1.20.1
